$ErrorActionPreference = "Stop"

# Setup Java Environment
$PotentialJavaHome = "$PSScriptRoot\tools\jdk\jdk-21.0.3+9"
if (Test-Path $PotentialJavaHome) {
    $env:JAVA_HOME = $PotentialJavaHome
    $env:Path = "$env:JAVA_HOME\bin;" + $env:Path
}

$SERVER_DIR = "$PSScriptRoot\server"

# Run generate_protos.ps1 to handle protobuf generation (like generate_protos.sh on Unix)
Write-Host "Generating Protobuf files..." -ForegroundColor Cyan
Set-Location $SERVER_DIR
& powershell -ExecutionPolicy Bypass -File generate_protos.ps1

Write-Host "Starting Server..." -ForegroundColor Green
Set-Location $SERVER_DIR

# Find mvn.cmd
$MvnCmd = Get-Command mvn.cmd -ErrorAction SilentlyContinue
if ($null -eq $MvnCmd) {
    # Try common installation paths if not in PATH
    $CommonPaths = @(
        "$PSScriptRoot\tools\maven\apache-maven-*\bin\mvn.cmd",
        "C:\Maven\apache-maven-*\bin\mvn.cmd",
        "C:\Program Files\apache-maven-*\bin\mvn.cmd",
        "C:\maven\bin\mvn.cmd"
    )
    $MvnCmd = Get-Item $CommonPaths -ErrorAction SilentlyContinue | Select-Object -First 1
}

if ($null -eq $MvnCmd) {
    Write-Warning "mvn.cmd not found in PATH or common locations. Falling back to 'mvn'."
    $MvnExecutable = "mvn"
} else {
    if ($MvnCmd -is [System.IO.FileInfo]) {
        $MvnExecutable = $MvnCmd.FullName
    } else {
        $MvnExecutable = "mvn.cmd"
    }
}

$DATA_DIR = Join-Path $PSScriptRoot "data"
# -T 1C: Parallel build (1 thread per core)
# -Dmaven.test.skip=true: Skip tests for faster development cycle
# -DskipProtobuf=true: Protos are already generated by generate_protos.ps1
$MvnArgs = @("-T", "1C", "compile", "exec:java", "-Dexec.mainClass=com.antigravity.App", "-Dapp.data.dir=$DATA_DIR", "-DskipProtobuf=true", "-Dmaven.test.skip=true")
& $MvnExecutable @MvnArgs
